import { Dapp } from '../../types'

export const Dapps: Dapp[] = [
    {
        name: 'Uniswap V3',
        url: 'https://app.uniswap.org/',
        description:
            'Uniswap v3 is a noncustodial automated market maker imple mented for the Ethereum Virtual Machine. In comparison to earlier versions of the protocol, Uniswap v3 provides increased capital efficiency and fine-tuned control to liquidity providers, improves the accuracy and convenience of the price oracle, and has a more lexible fee structure.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/UniswapV3.png',
        category: 'Exchange',
    },
    {
        name: 'Curve',
        url: 'https://curve.eth.link/',
        description: `Curve is DeFi's leading AMM, (Automated Market Maker).  Hundreds of liquidity pools have been launched through Curve's factory and incentivized by Curve's DAO.  Users rely on Curve's proprietary formulas to provide high liquidity, low slippage, low fee transactions among ERC-20 tokens.`,
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/Curve.png',
        category: 'Exchange',
    },
    {
        name: 'SushiSwap',
        url: 'https://app.sushi.com/',
        description:
            'Swap, earn, stack yields, lend, borrow, leverage all on one decentralized, community driven platform. Welcome home to DeFi.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/sushiswap.png',
        category: 'Exchange',
    },
    {
        name: 'Uniswap V2',
        url: 'https://app.uniswap.org/',
        description:
            'Uniswap V2, the second iteration of the Uniswap protocol, has been deployed to the Ethereum mainnet! Uniswap V2 has many new features and technical improvements compared with Uniswap V1 including: ERC20 / ERC20 Pairs Price Oracles Flash Swaps And much more!',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/UniswapV2.png',
        category: 'Exchange',
    },
    {
        name: 'Aave',
        url: 'https://app.aave.com/',
        description: 'Aave is an open source decentralized lending protocol that provides users with deposit and lending services.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/Aave.png',
        category: 'DeFi',
    },
    {
        name: 'dYdX',
        url: 'http://dydx.exchange/',
        description:
            'dYdX is the developer of a leading decentralized exchange on a mission to build open, secure, and powerful financial products.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/dYdX.png',
        category: 'Exchange',
    },
    {
        name: 'Compound',
        url: 'http://dydx.exchange/',
        description: 'Compound is an open-source protocol for algorithmic, efficient Money Markets on the Ethereum blockchain.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/Compound.jpeg',
        category: 'DeFi',
    },
    {
        name: '1inch',
        url: 'https://app.1inch.io/',
        description: '1inch Aggregation Protocol Facilitates Cost-Efficient and Secure Swap Trading Across Multiple Liquidity Sources.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/1inch.png',
        category: 'Exchange',
    },
    {
        name: 'DODO',
        url: 'https://app.dodoex.io/',
        description: `DODO's original PMM algorithm can help ordinary market makers and professional market makers provide the best liquidity with the least amount of funds. Efficient routing algorithms can compare prices across the entire network and provide traders with the most favorable transaction path.`,
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/dodo.jpeg',
        category: 'Exchange',
    },
    {
        name: 'Perpetual Protocol',
        url: 'https://app.perp.com/',
        description:
            'Perptual Protocol is a decentralized perpetual contract trading protocol with good liquidity, which is highly developer-friendly and composable.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/Perpetual.jpeg',
        category: 'DeFi',
    },
    {
        name: 'DeBank',
        url: 'https://debank.com/',
        description: 'The leading Web3 portfolio tracker supporting the largest number of DeFi protocols out of 36 chains.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/DeBank.jpeg',
        category: 'DeFi',
    },
    {
        name: 'Yearn.Finance',
        url: 'https://yearn.finance/',
        description:
            'Yearn Finance is a suite of products in Decentralized Finance (DeFi) that provides yield generation, lending aggregation, and more on the blockchain.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/YearnFinance.png',
        category: 'DeFi',
    },
    {
        name: 'LIDO',
        url: 'https://lido.fi/',
        description:
            'The Lido DAO is a decentralized autonomous organization that governs the liquid staking protocol through the voting power of governance token() holders to determine key parameters (e.g., set fees, assign node operators and oracles, etc.).',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/LIDO.png',
        category: 'DeFi',
    },
    {
        name: 'OpenSea',
        url: 'https://opensea.io/',
        description: 'Largest NFT marketplace. Buy, sell and discover items.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/OpenSea.png',
        category: 'Marketplace',
    },
    {
        name: 'The Sandbox',
        url: 'https://register.sandbox.game',
        description: 'The Sandbox is a virtual gaming world where players can build, own, and monetize their gaming experiences.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/TheSandbox.jpeg',
        category: 'Marketplace',
    },
    {
        name: 'Unstoppable Domains',
        url: 'https://unstoppabledomains.com/',
        description: 'Simplifying crypto payments and making web3 easy with NFT domains.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/UnstoppableDomain.jpeg',
        category: 'Marketplace',
    },
    {
        name: 'APENFT',
        url: 'https://apenft.io/',
        description: 'Register world-class artworks as NFTs on blockchain.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/APENFT.png',
        category: 'Marketplace',
    },
    {
        name: 'GALA',
        url: 'https://app.gala.games/',
        description: 'NFT game ecosystem on Ethereum and Binance smart chain.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/GALA.jpeg',
        category: 'Marketplace',
    },
    {
        name: 'XEN Crypto',
        url: 'https://xen.network/',
        description:
            'XEN crpyto is well packaged. It is said that it was founded by former Google engineer Jack Levin, inheriting the spirit of Bitcoin, and everyone can mint it for free.',
        trusted: false,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/xen.jpeg',
        category: 'DeFi',
    },
    {
        name: 'Bancor',
        url: 'https://www.bancor.network/',
        description: 'Bancor is a liquidity protocol that enables automated, decentralized exchange.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/Bancor.png',
        category: 'Exchange',
    },
    {
        name: 'Balancer',
        url: 'https://balancer.fi/',
        description:
            'Balancer Protocol allows for automated portfolio management and providing liquidity turning the concept of an index fund on its head: instead of paying fees to portfolio managers, you collect fees from traders who rebalance your portfolio by following arbitrage opportunities.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/Balancer.png',
        category: 'Exchange',
    },
    {
        name: '0x Protocol',
        url: 'https://www.0x.org/',
        description: 'Trusted exchange infrastructure for the internet.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/0xProtocol.jpeg',
        category: 'Exchange',
    },
    {
        name: 'ApeSwap',
        url: 'https://apeswap.finance/',
        description:
            'ApeSwap is the DeFi hub on BNB Chain, Polygon and Ethereum focused on providing everyone an accessible, transparent and secure experience.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/ape.png',
        category: 'DeFi',
    },
    {
        name: 'MakerDao',
        url: 'https://makerdao.com/',
        description:
            'The Maker Protocol, also known as the Multi-Collateral Dai (MCD) system, allows users to generate Dai by leveraging collateral assets approved by “Maker Governance.”',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/MakerDao.jpeg',
        category: 'DeFi',
    },
    {
        name: 'Synthetix',
        url: 'https://synthetix.io/',
        description:
            'Synthetix is a decentralized synthetic asset platform. These assets - synths - are crypto-backed synthetic assets that track the value of underlying assets and allow exposure to an asset without the requirement of actually holding it.',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/ethereum/dapp/assets/Synthetix.png',
        category: 'DeFi',
    },
]
