import { Dapp } from '../../types'

export const Dapps: Dapp[] = [
    {
        name: 'PancakeSwap',
        url: 'https://pancakeswap.finance/',
        description: 'Most popular and feature-rich DeFi DApp and AMM',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/PancakeSwap.png',
        category: 'Exchange',
    },
    {
        name: 'Enchanter Finance',
        url: 'https://app.enchanter.fi/',
        description: 'The 1st Social Trading AMM DEX',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/EnchanterLogo.png',
        category: 'Exchange',
    },
    {
        name: 'ItsRare Marketplace',
        url: 'https://aptos.itsrare.app/',
        description: 'A Gateway for creating, discovering and trading digital asset on the Aptos Blockchain',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Itrare.png',
        category: 'Marketplace',
    },
    {
        name: 'Kana Labs',
        url: 'https://www.kanalabs.io/',
        description: 'DeFi platform where users across multiple blockchains',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Kana.png',
        category: 'Finance',
    },
    {
        name: 'Proton Sale',
        url: 'https://protonsale.io/',
        description: 'The launchpad Protocol',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/ProtonSale.jpeg',
        category: 'Utilities',
    },
    {
        name: 'Souffl3',
        url: 'https://souffl3.com/',
        description: 'Smart Trading NFT Marketplace',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Souffl3.png',
        category: 'Marketplace',
    },
    {
        name: 'Aptoswap',
        url: 'https://aptoswap.net/',
        description: 'Lighweight & Powerful Swap Platform',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/AptosSwap.png',
        category: 'Finance',
    },
    {
        name: 'Topaz',
        url: 'https://www.topaz.so/',
        description: 'A Powerful, Safety, and Scalable NFT Marketplace on Aptos',
        trusted: true,
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Topaz.svg',
        category: 'Marketplace',
    },
    {
        name: 'Seam Money',
        url: 'https://www.seam.money/',
        description: 'Structured DeFi Products',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Seam.png',
        category: 'Finance',
    },
    {
        name: 'Econia',
        url: 'https://www.econia.dev/',
        description: 'Hyper-parallelized on-chain CLOB for the Aptos blockchain',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Econia.png',
        category: 'Others',
    },
    {
        name: 'Tortuga Finance',
        url: 'https://dev.app.tortuga.finance/',
        description: 'Tortuga Finance is the most trusted liquid staking protocol on Aptos',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Tortuga.png',
        category: 'Finance',
    },
    {
        name: 'Aries Markets',
        url: 'https://ariesmarkets.xyz/',
        description:
            'Aries Market is a decentralised margin trading protocol on Aptos. Lend, borrow and trade with margin via a fully on-chain order book',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/AriesMarket.png',
        category: 'Exchange',
    },
    {
        name: 'Tsunami',
        url: 'https://tsunami.finance/',
        description: 'Trade spot & perpetuals with 0% slippage.',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Tsunami.png',
        category: 'Exchange',
    },
    {
        name: 'Mojito',
        url: 'https://www.mojito.markets/',
        description: 'Decentralised Prediction Markets on the blockchain',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Mojito.jpeg',
        category: 'Others',
    },
    {
        name: 'Momentum Safe',
        url: 'https://app.m-safe.io/',
        description: 'Multi-signature wallet solution The most secure digital assets management and analytics tool on Move',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Momentum.png',
        category: 'Others',
    },
    {
        name: 'Celer cBridge',
        url: 'https://cbridge.celer.network/1/12360001/USDC',
        description: 'cBridge introduces the best-in-class cross-chain token bridging experience with deep liquidity for users',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Celer.png',
        category: 'Finance',
    },
    {
        name: 'Abel finance',
        url: 'https://abelfinance.xyz/#/markets',
        description: 'The first fully decentralized multiple cross-chain lending Defi running on the APTOS network',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Abel.jpeg',
        category: 'Finance',
    },
    {
        name: 'Meerio',
        url: 'https://meeiro.xyz/',
        description: 'A user driven IDO launchpad on Aptos Network connecting retail investors and projects together.',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Meerio.svg',
        category: 'Utilities',
    },
    {
        name: 'Meson.fi',
        url: 'https://meson.fi/fewcha',
        description: 'Meson provides minute-fast swaps with almost-zero fee & slippage across all major blockchains.',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Meson.png',
        category: 'Finance',
    },
    {
        name: 'Aptin',
        url: 'https://app.aptin.io/',
        description:
            'Aptin is a decentralised non-custodial liquidity market protocol where users can participate as depositors or borrowers',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/Aptin.png',
        category: 'Finance',
    },
    {
        name: 'BlueMove',
        description: 'Home to the next generation of digital creators.',
        url: 'https://sui.bluemove.net',
        img: 'https://raw.githubusercontent.com/nixjs/coin-dapp-wallet-list/main/src/aptos/dapp/assets/bluemove.jpeg',
        category: 'Marketplace',
    },
]
